import { User } from './interface/UserInterface';

export const UsersExample: User[] = [
  {
    name: 'Clara Ferraz',
    username: 'claraferraz',
    posts: 10,
    id: '9680e272-5c8b-457a-b716-daadcba84e8c',
    email: 'clara@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et ma',
    insta: 'http://instagram.com/',
    linkedin: 'http://linkedin.com',
    github: 'http://github.com',
  },
  {
    name: 'Breno Leal',
    username: 'brenoleal',
    posts: 15,
    id: 'e2085ca8-ae0f-4152-ae8e-9b75cb5ae486',
    email: 'breno@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et ma',
    insta: 'http://instagram.com/',
    linkedin: 'http://linkedin.com',
    github: 'http://github.com',
  },
  {
    name: 'Kaio Paulo',
    username: 'kaiopaulo',
    posts: 15,
    id: '0637ca29-e2c2-4190-b9be-40a62b5f7068',
    email: 'kaio@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et ma',
    insta: 'http://instagram.com/',
    linkedin: 'http://linkedin.com',
    github: 'http://github.com',
  },
  {
    name: 'Gustavo Santos',
    username: 'gustavosantos',
    posts: 15,
    id: '4454bb54-225d-4898-a8f5-1cf6688ad40b',
    email: 'gustavo@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et ma',
    insta: 'http://instagram.com/',
    linkedin: 'http://linkedin.com',
    github: 'http://github.com',
  },
];
